apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hue-mqtt-bridge.fullname" . }}-config
  labels:
{{ include "hue-mqtt-bridge.labels" . | indent 4 }}
data:
  config.json: |-
    {{- .Values.config | nindent 4 }}