apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hue-mqtt-bridge.fullname" . }}
  labels:
    {{- include "hue-mqtt-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hue-mqtt-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hue-mqtt-bridge.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "hue-mqtt-bridge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
            # httpGet:
              # path: /
              # port: http
          # readinessProbe:
            # httpGet:
              # path: /
              # port: http
          volumeMounts:
            - name: config-json
              mountPath: config/config.json
              subPath: config.json
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config-json
        configMap:
          name: {{ include "hue-mqtt-bridge.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
