{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hue-mqtt-bridge.serviceAccountName" . }}
  labels:
{{ include "hue-mqtt-bridge.labels" . | nindent 4 }}
{{- end -}}
