apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}-config
  labels:
{{ include "eclipse-mosquitto.labels" . | indent 4 }}
data:
  mosquitto.conf: |-
    {{- .Values.config | nindent 4 }}
  healthz: |-
    {{- .Values.healthz | nindent 4 }}
  healthzscript: |-
    {{- .Values.healthzscript | nindent 4 }}
