apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}-certs
  labels:
{{ include "eclipse-mosquitto.labels" . | indent 4 }}
data:
  ca.crt: |-
    {{- .Files.Get "certs/server-ca.crt" | nindent 4 }}
  server.crt: |-
    {{- .Files.Get "certs/server.crt"  | nindent 4 }}
  server.key: |-
    {{- .Files.Get "certs/server.key" | nindent 4 }}