apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels:
{{ include "eclipse-mosquitto.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: {{ default "TCP" $value.protocol }}
  {{ if (not (empty $value.nodePort)) }}
      nodePort: {{ $value.nodePort }}
  {{ end }}
  {{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "eclipse-mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
