apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snapcast-client.fullname" . }}
  labels:
    {{- include "snapcast-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snapcast-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snapcast-client.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "snapcast-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
        {{- if .Values.extraVars }}
        {{- range $key, $value := .Values.extraVars }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: var-run-pulse
            mountPath: /var/run/pulse
      volumes:
      - hostPath:
          path: /var/run/pulse
          type: Directory
        name: var-run-pulse
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
