{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snapcast-client.serviceAccountName" . }}
  labels:
{{ include "snapcast-client.labels" . | nindent 4 }}
{{- end -}}
