#!/usr/bin/env bash

set -e

#if ! command -v helm-docs > /dev/null 2>&1; then
#    echo "Please install helm-docs to run the pre-commit hook! https://github.com/norwoodj/helm-docs#installation"
#    exit 1
#fi
# helm-docs "${@}"
DOCKER_COMMAND="podman run --rm -v /home/gxw/kubernetes/my-helm-charts/charts:/helm-docs grewhit25/helm-docs-arm"
if ! $DOCKER_COMMAND > /dev/null 2>&1; then
    echo "docker command fail"
    exit 1
fi
echo "README.md Documentation generated"
