apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpd.fullname" . }}
  labels:
    {{- include "mpd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mpd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mpd.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mpd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
    {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.ports }}
          ports:
          {{- range $key, $value := . }}
            - name: "{{ $key }}"
              containerPort: {{ $value.port }}
              protocol: {{ default "TCP" $value.protocol }}
          {{- end }}
        {{- end }}  
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: snapcast-mpd-fifo
              mountPath: /output
              #subPath: mpd_fifo
      volumes:
        #- name: snapcast-mpd-fifo
        #  emptyDir: {}
        #- hostPath:
        #    path: /tmp
        #  name: snapcast-mpd-fifo
        - name: snapcast-mpd-fifo
        {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.hostPath }}
          hostPath:
            path: {{.Values.persistence.hostPath}}
            type: Directory
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "mpd.fullname" . }}{{- end }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
