{{- if .Values.snapcast_serverConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "snapcast-server.fullname" . }}-file-config'
  labels:
    app.kubernetes.io/name: {{ include "snapcast-server.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "snapcast-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.extraLabels }}
    {{- toYaml .Values.extraLabels | nindent 4 }}
  {{- end }}
data:
  snapserver.conf: |-
    {{- .Values.snapcast_serverConfig | nindent 4 }}
{{- end }}
