apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapcast-server.fullname" . }}
  labels:
    {{- include "snapcast-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: {{ default "TCP" $value.protocol }}
  {{- end }}
{{- end }}
  selector:
    {{- include "snapcast-server.selectorLabels" . | nindent 4 }}
